kind: pipeline
type: docker
name: default

# disable default git clone
#clone:
#  disable: true

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world

## VM 掛載路徑
volumes:
  - name: cache
    host:
      path: /usr/local/app/cache
  - name: docker
    host:
      path: /var/run/docker.sock

## 載入 docker config 設定
image_pull_secrets:
  - dockerconfigjson

# 觸發 pipeline 條件
trigger:
  ref:
    include: [refs/heads/develop, refs/heads/qatest, refs/heads/int, refs/tags/v*, refs/tags/t*, refs/tags/release-v*]
