kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: alpine
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password

# 觸發 pipeline 條件
trigger:
  ref:
    include: [refs/heads/master]