kind: pipeline
type: docker
name: default

# disable default git clone
clone:
  disable: true

## 定義基本路徑
workspace:
  base: /go/src
  path: ${DRONE_REPO_NAME}

steps:
  - name: build
    image: alpine
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password

# 觸發 pipeline 條件
trigger:
  ref:
    include: [refs/heads/master]